version: '3.3'
services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/NewsPortal
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=YouMore
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=NewsPortal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YouMore
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
